displayName=Better Widget Hider
author=Jake
description=Hide specific parts of game interfaces (HUDs, overlays) by widget ID
tags=jake,widget,widgets,interface,hide,hider,hud,overlay,clean,declutter,component,id,gotr
plugins=com.betterwidgethider.BetterWidgetHiderPlugin
build=standard
